name: Shibacraft
version: "${version}"
main: net.shibacraft.shibacraft.Shibacraft
api-version: 1.17
authors: [ SKJOLBERG ]
description: Plugin of Shibacraft Network - Survival
website: https://shibacraft.net
softdepend: [PlaceholderAPI, LuckPerms]

commands:
  shibacraft:
    description: Main command
    aliases: [sh]
  ayuda:
    description: Server help
  discord:
    description: Server discord
  mapa:
    description: Server map
  wallet:
    description: Server wallet
  web:
    description: Server web
  wiki:
    description: Server wiki
  presidente:
    description: President command
  ciudadano:
    description: Citizen command
permissions:
  shibacraft.admin:
    description: Allows all admin permissions
    default: op
    children:
      shibacraft.presidente: true
      shibacraft.ciudadano: true
  shibacraft.presidente:
    description: President
    default: false
  shibacraft.ciudadano:
    description: Citizen
    default: true